name: '🌀 Z Activity Metrics'

on:
  schedule:
    - cron: "0 0/6 * * *"
  workflow_dispatch:
  push:
    paths: ['.github/workflows/activity_metrics.yml']
  pull_request:
    paths: ['.github/workflows/activity_metrics.yml']
 
jobs:
  metrics-activity:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@eea0e216b8b9daa748417a2e53ca32d3eee0a1da
        with:
          filename: 'metrics/plugin/projects/projects.svg'
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          user: z-shell
          plugin_projects: yes
          plugin_projects_descriptions: yes
          plugin_projects_limit: 5
