name: '🌀 Z Activity Metrics'

on:
  schedule:
    - cron: "0 0/3 * * *"
  workflow_dispatch:
  push:
    paths: ['.github/workflows/activity_metics.yml']
  pull_request:
    paths: ['.github/workflows/activity_metics.yml']
 
jobs:
  metrics-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@eea0e216b8b9daa748417a2e53ca32d3eee0a1da
        with:
          filename: 'metrics/plugin/activity/activity.svg'
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          user: z-shell
          plugin_activity: yes
          plugin_activity_limit: 6
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, review, ref/create, member 
          plugin_activity_ignored: renovate-bot, renovate, crowdin-bot, allcontributors, allcontributors-bot, ImgBotApp
      - uses: lowlighter/metrics@eea0e216b8b9daa748417a2e53ca32d3eee0a1da
        with:
          filename: 'metrics/plugin/projects/projects.svg'
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          user: z-shell
          plugin_projects: yes
          plugin_projects_descriptions: yes
