---
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@483689a71cf9d3a0bbdd79d23e00646ef4124391
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_PAT }}
        with:
          source-directory: '.github/sync/project_docs/CODE_OF_CONDUCT.md'
          destination-github-username: 'z-shell'
          destination-repository-name: 'zw'
          user-email: digital-teams@pm.me
          target-branch: main
          target-directory: .github
