---
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_PAT }}
        with:
          source-directory: '.github/sync/project_docs'
          destination-github-username: 'z-shell'
          destination-repository-name: 'zw'
          user-email: digital-teams@pm.me
          target-branch: main
          target-directory: .github
