name: '🌀 Z Community Metrics' 

on:
  schedule:
    - cron: "06 6 * * *"
  workflow_dispatch:
  push:
    paths: ['.github/workflows/community.yml']
  pull_request:
    paths: ['.github/workflows/community.yml']

jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@eea0e216b8b9daa748417a2e53ca32d3eee0a1da
        with:
          filename: 'metrics/plugin/contributors/zi/contributors.svg'
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          template: repository
          user: z-shel
          repo: zi
          plugin_contributors: yes
          plugin_contributors_contributions: yes
      - uses: lowlighter/metrics@eea0e216b8b9daa748417a2e53ca32d3eee0a1da
        with:
          filename: 'metrics/plugin/contributors/zw/contributors.svg'
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          template: repository
          user: z-shel
          repo: zw
          plugin_contributors: yes
          plugin_contributors_contributions: yes
      - uses: lowlighter/metrics@eea0e216b8b9daa748417a2e53ca32d3eee0a1da
        with:
          filename: 'metrics/plugin/contributors/f-sy-h/contributors.svg'
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          template: repository
          user: z-shel
          repo: f-sy-h
          plugin_contributors: yes
          plugin_contributors_contributions: yes
