name: '🌀 Z Metrics'

on:
  schedule:
    - cron: "02 02 * * *"
  workflow_dispatch:
  push:
    paths: ['.github/workflows/metrics.yml']
  pull_request:
    paths: ['.github/workflows/metrics.yml']

jobs:
  metrics:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rep: ["zi", "zw"]
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@eea0e216b8b9daa748417a2e53ca32d3eee0a1da
        with:
          template: repository
          filename: 'metrics/plugin/followup/${{ matrix.rep }}/indepth.svg'
          token: ${{ secrets.ORG_TOKEN }}
          user: z-shell
          repo: ${{ matrix.rep }}
          plugin_lines: yes
          plugin_followup: yes
          plugin_repositories: yes
      - uses: lowlighter/metrics@eea0e216b8b9daa748417a2e53ca32d3eee0a1da
        with:
          filename: 'metrics/plugin/repositories/repositories.svg'
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          plugin_repositories: yes
          plugin_repositories_featured: z-shell/zi, z-shell/zw, z-shell/f-sy-h, z-shell/community
  metrics-pagespeed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@eea0e216b8b9daa748417a2e53ca32d3eee0a1da
        with:
          filename: 'metrics/plugin.svg'
          token: ${{ secrets.ORG_TOKEN }}
          user: z-shell
      - uses: lowlighter/metrics@eea0e216b8b9daa748417a2e53ca32d3eee0a1da
        with:
          filename: 'metrics/plugin/pagespeed/detailed.svg'
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://z.digitalclouds.dev
  metrics-indepth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@eea0e216b8b9daa748417a2e53ca32d3eee0a1da
        with:
          filename: 'metrics/plugin/followup/indepth.svg'
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          user: z-shell
          plugin_followup: yes
          plugin_followup_indepth: yes


