name: Metrics CI-1

on:
  workflow_dispatch:
  schedule:
    - cron: '03 03 * * *'

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ORG_TOKEN }}
          user: z-shell
      - name: Latest tweets
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.tweets.svg
          token: NOT_NEEDED
          base: ""
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_BEARER_TOKEN }}
          plugin_tweets_user: zshell_zi
      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.followup.indepth.svg
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          user: z-shell
          plugin_followup: yes
          plugin_followup_indepth: yes
      - name: GitHub Discussions
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.discussions.svg
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          plugin_discussions: yes
          plugin_discussions_categories_limit: 8
      - name: Contributors with contributions count
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.zi.contributors.contributions.svg
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          template: repository
          repo: zi
          plugin_contributors: yes
          plugin_contributors_contributions: yes
      - name: Contributors with contributions count
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.zw.contributors.contributions.svg
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          template: repository
          repo: zw
          plugin_contributors: yes
          plugin_contributors_contributions: yes
