name: Metrics CI

on:
  workflow_dispatch:
  schedule:
    - cron: '03 03 * * *'

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ORG_TOKEN }}
          user: z-shell
      - name: Latest tweets
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.tweets.svg
          token: NOT_NEEDED
          base: ""
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_BEARER_TOKEN }}
          plugin_tweets_user: zshell_zi
      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.followup.indepth.svg
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          user: z-shell
          plugin_followup: yes
          plugin_followup_indepth: yes
      - name: GitHub Discussions
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.discussions.svg
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          plugin_discussions: yes
          plugin_discussions_categories_limit: 8
      - name: Detailed report
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.pagespeed.detailed.svg
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://z.digitalclouds.dev
      - name: Project from a repository
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.projects.svg
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          plugin_projects: yes
          plugin_projects_repositories: z-shell/zi/projects/2
          plugin_projects_descriptions: yes
