name: Metrics CI-3

on:
  workflow_dispatch:
  schedule:
    - cron: '03 03 * * *'

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.ORG_TOKEN }}
          user: z-shell
      - name: Latest tweets
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.tweets.svg
          token: NOT_NEEDED
          base: ""
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_BEARER_TOKEN }}
          plugin_tweets_user: zshell_zi
      - name: RSS dev.to/z-shell
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.dev.zshell.rss.svg
          token: NOT_NEEDED
          base: ""
          plugin_rss: yes
          plugin_rss_source: https://dev.to/feed/z-shell
          plugin_rss_limit: 2
      - name: RSS dev.to/tag/zsh
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.dev.tag.zsh.rss.svg
          token: NOT_NEEDED
          base: ""
          plugin_rss: yes
          plugin_rss_source: https://dev.to/feed/tag/zsh
          plugin_rss_limit: 4
