name: STATISTICS

on:
  workflow_dispatch:
  schedule:
    - cron: "02 02 * * *"
  push:
    paths: ['.github/workflows/metrics.yml']

jobs:
  metrics:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rep: ["zi", "zw"]
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@eea0e216b8b9daa748417a2e53ca32d3eee0a1da
        with:
          filename: metrics/featured.repositories.svg
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          user: z-shell
          plugin_repositories: yes
          plugin_repositories_featured: zi zw f-sy-h community
      - uses: lowlighter/metrics@eea0e216b8b9daa748417a2e53ca32d3eee0a1da
        with:
          template: repository
          filename: "metrics/${{ matrix.rep }}/indepth.repository.svg"
          token: ${{ secrets.ORG_TOKEN }}
          user: z-shell
          repo: ${{ matrix.rep }}
          plugin_lines: yes
          plugin_followup: yes
          plugin_repositories: yes
  metrics-pagespeed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@eea0e216b8b9daa748417a2e53ca32d3eee0a1da
        with:
          filename: metrics/plugin.svg
          token: ${{ secrets.ORG_TOKEN }}
          user: z-shell
      - uses: lowlighter/metrics@eea0e216b8b9daa748417a2e53ca32d3eee0a1da
        with:
          filename: metrics/plugin.pagespeed.detailed.svg
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://z.digitalclouds.dev
  metrics-indepth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@eea0e216b8b9daa748417a2e53ca32d3eee0a1da
        with:
          filename: metrics/plugin.followup.indepth.svg
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          user: z-shell
          plugin_followup: yes
          plugin_followup_indepth: yes
  metrics-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@eea0e216b8b9daa748417a2e53ca32d3eee0a1da
        with:
          filename: metrics/plugin.activity.svg
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          user: z-shell
          plugin_activity: yes
          plugin_activity_limit: 4
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, review, ref/create
          plugin_activity_ignored: renovate-bot, renovate, crowdin-bot, allcontributors, allcontributors-bot, ImgBotApp
  metrics-projecs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@eea0e216b8b9daa748417a2e53ca32d3eee0a1da
        with:
          filename: metrics/plugin.projects.svg
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          user: z-shell
          plugin_projects: yes
          plugin_projects_descriptions: yes
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@eea0e216b8b9daa748417a2e53ca32d3eee0a1da
        with:
          filename: metrics/plugin.starlists.svg
          token: NOT_NEEDED
          base: ""
          user: z-shell
          plugin_starlists: yes
          plugin_starlists_limit_repositories: 2
          plugin_starlists_only: TC39
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@eea0e216b8b9daa748417a2e53ca32d3eee0a1da
        with:
          filename: metrics/plugin.starlists.languages.svg
          token: NOT_NEEDED
          base: ""
          user: z-shell
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 8
          plugin_starlists_limit_repositories: 0
          plugin_starlists_only: Awesome
