name: COMMUNITY-CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1/6 * * *'

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ss-o/metrics@latest
        with:
          filename: metrics/plugin.svg
          token: ${{ secrets.ORG_TOKEN }}
          user: z-shell
      - name: GitHub Discussions
        uses: ss-o/metrics@latest
        with:
          filename: metrics/plugin.discussions.svg
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          plugin_discussions: yes
          plugin_discussions_categories_limit: 10
      - name: Contributors with contributions count
        uses: ss-o/metrics@latest
        with:
          filename: metrics/zi.contributors.contributions.svg
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          template: repository
          repo: zi
          plugin_contributors: yes
          plugin_contributors_contributions: yes
