name: READER

on:
  workflow_dispatch:
  schedule:
    - cron: "12 * * * 0/2"

jobs:
  metrics-tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@3553137563208ff64cb470b8f23fd8c503627f32
        with:
          filename: metrics/plugin.tweets.svg
          token: NOT_NEEDED
          base: ""
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_BEARER_TOKEN }}
          plugin_tweets_user: zshell_zi
  metrics-rss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@3553137563208ff64cb470b8f23fd8c503627f32
        with:
          filename: metrics/rrs/plugin.dev.zshell.rss.svg
          token: NOT_NEEDED
          base: ""
          plugin_rss: yes
          plugin_rss_source: https://dev.to/feed/z-shell
          plugin_rss_limit: 3
      - uses: lowlighter/metrics@3553137563208ff64cb470b8f23fd8c503627f32
        with:
          filename: metrics/rss/plugin.dev.tag.zsh.rss.svg
          token: NOT_NEEDED
          base: ""
          plugin_rss: yes
          plugin_rss_source: https://dev.to/feed/tag/zsh
          plugin_rss_limit: 3
#      - name: Top answers from stackoverflow
#        uses: ss-o/metrics@latest
#        with:
#          filename: metrics/plugin.stackoverflow.svg
#          token: NOT_NEEDED
#          base: ""
#          plugin_stackoverflow: yes
#          plugin_stackoverflow_user: digitalclouds
#          plugin_stackoverflow_sections: answers-top
#          plugin_stackoverflow_limit: 2
