---
name: REPO-READER

on:
  workflow_dispatch:
  schedule:
    - cron: "02 02 * * *"

jobs:
  metrics:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rep: ["zi", "zw"]
    steps:
      - uses: actions/checkout@v3
      - uses: ss-o/metrics@latest
        with:
          filename: "metrics/${{ matrix.rep }}/repository.svg"
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          plugin_repositories: yes
          plugin_repositories_featured: ${{ matrix.rep }}
          
  metrics-indepth:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rep: ["zi", "zw"]
    steps:
      - uses: actions/checkout@v3
      - uses: ss-o/metrics@latest
        with:
          template: repository
          filename: "metrics/${{ matrix.rep }}/indepth.repository.svg"
          token: ${{ secrets.ORG_TOKEN }}
          user: z-shell
          repo: ${{ matrix.rep }}
          plugin_lines: yes
          plugin_followup: yes
