---
name: REPO-READER

on:
  workflow_dispatch:
  schedule:
    - cron: "02 02 * * *"

jobs:
  metrics:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rep: ["zi", "zw"]
    steps:
      - uses: actions/checkout@v3
      - uses: lowlighter/metrics@3553137563208ff64cb470b8f23fd8c503627f32
        with:
          filename: metrics/featured.repositories.svg
          token: ${{ secrets.ORG_TOKEN }}
          base: ""
          user: z-shell
          plugin_repositories: yes
          plugin_repositories_featured: z-shell/zi z-shell/zw
      - uses: lowlighter/metrics@3553137563208ff64cb470b8f23fd8c503627f32
        with:
          template: repository
          filename: "metrics/${{ matrix.rep }}/indepth.repository.svg"
          token: ${{ secrets.ORG_TOKEN }}
          user: z-shell
          repo: ${{ matrix.rep }}
          plugin_lines: yes
          plugin_followup: yes
          plugin_repositories: yes
