---
name: ♻️ Sync Labels

on:
  push:
    branches: [$default-branch]
    paths:
      - .github/lib/labels.yml
  workflow_dispatch:

jobs:
  labels:
    name: ♻️ Sync labels
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
        with:
          repository: z-shell/.github
          path: ./.github
      - name: ♻️ Fetch Labels
        run: |
          mkdir -p ./.github/lib
          curl -fsSl https://raw.githubusercontent.com/z-shell/.github/main/.github/lib/labels.yml -o ./.github/labels.yml
      - name: 🚀 Run Label Syncer
        uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
